icu_db_ro:
  host: localhost
  database: icu_db_copy
  username: ro_username
  password: ro_password
  encoding: latin1

icu_db_rw:
  host: localhost
  database: icu_db_copy
  username: rw_username
  password: rw_password
  encoding: latin1

secret_key_base: 4fbd352d214c2118a7fc152173de8dd358dcd07289a8eb75fe332e279848a905fd1228b6e51e4ec60c14b41d69c93eecea7a35bb8854d99356a0f13091bd08b7

hasher: "Digest::MD5.hexdigest(salt + pass)"

session_key: _ratings_session

google_site_verification: nDJOyeKUA0Uk1ptyAZDbASyXU_o6tEo7-6VS9b0v1xs
