development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ratings_development
  pool: 5
  username: ratings
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ratings_test
  pool: 5
  username: ratings
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ratings_production
  pool: 5
  username: ratings
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false
